# Generated by Django 4.1.6 on 2023-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_decription_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='img.jpg', upload_to='image/%M', verbose_name='Картинка поста'),
            preserve_default=False,
        ),
    ]
