# Generated by Django 4.2 on 2023-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                default="cat_img/categ.png",
                upload_to="image/%M",
                verbose_name="Картинка поста",
            ),
        ),
    ]
