# Generated by Django 4.1.7 on 2023-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.TextField(blank=True, null=True, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.TextField(blank=True, null=True, verbose_name="Фамилия"),
                ),
                (
                    "email",
                    models.TextField(blank=True, null=True, verbose_name="Почта"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
