# Generated by Django 4.1.7 on 2023-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(blank=True, null=True, verbose_name="Название"),
                ),
                ("price", models.TextField(blank=True, null=True, verbose_name="Цена")),
                (
                    "image",
                    models.IntegerField(blank=True, null=True, verbose_name="Картинка"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "db_table": "products",
                "managed": False,
            },
        ),
    ]
