# Generated by Django 4.1.6 on 2023-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='cat_img/categ.png', upload_to='cat_img', verbose_name='Картинка категории'),
        ),
    ]
